pws-google:
    application-name: "Some app"
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_CLIENT_REDIRECT_URI}

quarkus:
    log:
        level: ${LOG_LEVEL}
